---
title: "map"
author: "Lambridge"
date: "2021/12/11"
output: html_document
---
#load the package
```{r}
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
```
#read all the spatial data
#reproject it


```{r}
OSM <- st_read(here::here("prac5_data",
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  #select the hotel only
  filter(fclass == "hotel")
```

```{r}
Worldcities <- st_read(here::here("prac5_data",
                                  "World_Cities.shp")) %>%
  st_transform(., 27700)
UK_outline <- st_read(here::here("prac5_data", 
                                 "gadm36_GBR_0.shp")) %>%
  st_transform(., 27700)
```


```{r}
Londonborough <- st_read(
  here::here(
    "prac5_data",
    "statistical-gis-boundaries-london",
    "ESRI",
    "London_Borough_Excluding_MHW.shp"
  )
) %>%
  st_transform(., 27700)
```


read in the csv 
make it into spatial data

```{r}
Airbnb <- read_csv("prac5_data/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"),
           crs = 4326) %>%
  st_transform(., 27700) %>%
  #select entire places that are available all year
  filter(room_type == 'Entire home/apt' & availability_365 == '365')
# entire 不要写错了
```

make a function fot the join 
```{r}
Joinfun <- function(data1,data2)
{
  output <- data1 %>% 
    st_join(Londonborough,.) %>% 
    add_count(GSS_CODE,name="hotels_in_borough")
    
  return (output)
}

#use this function for hotels 
Hotels <- Joinfun(OSM,Londonborough)
#then for the airbnb
Airbnb <- Joinfun(Airbnb,Londonborough)

Worldcities2 <- Worldcities %>% 
  filter (CNTRY_NAME=="United Kingdom"&
            Worldcities$CITY_NAME=='Birmingham'|
            Worldcities$CITY_NAME=='London'|
            Worldcities$CITY_NAME=='Edinburgh')
newbb <- c(xmin=-29600,ymin=54008,xmax=655696,ymax=1000000)

UK_outlinecrop <- UK_outline %>%
  st_crop(.,newbb)

Hotels <- Hotels %>% 
  group_by(.,GSS_CODE,NAME) %>% 
  summarise("Accomodation count" = unique(hotels_in_borough))
  
Airbnb <- Airbnb %>% 
  group_by(.,GSS_CODE,NAME) %>% 
  summarise("Accomodation count" = unique(hotels_in_borough))
```
```{r}
tmap_mode("plot")

#set the breaks 
#for our mapped data 
breaks = c(0,5,12,26,57,257)
tm1 <- tm_shape(Hotels)+
  tm_polygons("Accomodation count",
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)",position = c(0,0.85,size=1.5))

tm2 <- tm_shape(Airbnb)+
  tm_polygons("Accomodation count",
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)",position = c(0,0.85,size=1.5))

tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(Worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

legend <- tm_shape(Hotels) +
  tm_polygons("Accomodation count",
              palette="PuBu")+
  tm_scale_bar(position = c(0.2,0.04),text.size = 0.6)+
  tm_compass(north = 0, position = c(0.65,0.6))+
  tm_layout(legend.only = TRUE,legend.position = c(0.2,0.25),asp=0.1)+
  tm_credits("OSM",position = c(0.0,0.0))

t = tmap_arrange(tm1,tm2,tm3,legend,ncol=2)
t

```
# other way to arrage the map




```{r}
library(grid)
grid.newpage()

pushViewport(viewport(layout = grid.layout(2,2)))
print(tm1,vp=viewport(layout.pos.col = 1,layout.pos.row = 1,height = 5))
print(tm2,vp=viewport(layout.pos.col = 2,layout.pos.row = 1,height = 5))
print(tm1,vp=viewport(layout.pos.col = 1,layout.pos.row = 2,height = 5))
print(legend,vp=viewport(layout.pos.col = 2,layout.pos.row = 2,height = 5))

```



#插入地图


```{r}
Londonbb = st_bbox(Airbnb,
                   crs = st_crs(Airbnb)) %>%
  st_as_sfc
#Return bounding of a simple feature or simple feature set


```

```{r}
main <- tm_shape(Airbnb, bbbox = Londonbb) +
  tm_polygons("Accomodation count",
              breaks = breaks,
              palette = "PuBu") +
  tm_scale_bar(position = c("left", "bottom", text.size = .75)) +
  tm_layout(
    legend.position = c("right", "top"),
    legend.text.size = .75,
    legend.title.size = 1.1,
    frame = FALSE
  ) +
  tm_credits("(c)OpenstreeMap contrbutors and Airbnb", position = c(0.0, 0.0)) +
  tm_compass(type = "8star", position = c(0.06, 0.1)) +
  tm_layout(inner.margins = c(0.002, 0.002, 0.002, 0.2))
main
```


```{r}
inset=tm_shape(UK_outlinecrop)+tm_polygons()+
  tm_shape(Londonbb)+
  tm_borders(col = "grey40",lwd=3)+
  tm_layout(frame=FALSE,
            bg.color = "transparent")+
  tm_shape(Worldcities2)+
  tm_symbols(col="red",scale=.5)+
  tm_text("CITY_NAME",xmod=-1.5,ymod = -0.5)

inset
```

```{r}
library(grid)
main
print(inset,vp = viewport(0.86,0.29,width=0.5,height=0.55))
```
Export

```{r}

tmap_save(t,'hotelsandairbnbR.png')

library(grid)
tmap_save(main,insets_tm = inset,insets_vp = viewport(x=0.86,y=0.29,width = .5,height = .55),filename = "testfilename",dpi=600)


```


